name: "Отчет о дефектах"
description: "Шаблон для создания отчета о дефектах"
title: "[Ошибка]: "
labels: ["bug"]
body:
    type: textarea
    id: desc
    attributes:
      label: Описание
      description: Описание дефекта
      placeholder: введите описание дефекта
    validations:
      required: true 